# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c6d0df19457d622375c055ad0fdc820b252f0af204c40875f803a52753b9e3dc1d1a076b360607ecbb232f19817439edcbaac01f9d014ee614186ae9fab9b3a

test:
  secret_key_base: ccdff4e71f22b8d838c436b58ce055bcb0b4e6545ad2afe6cd2c9575d013d7661f3cd38ab6604bfc8e2078dd89d1e592c25da26431fcfcc05b68aaa71bab1b49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
